### ISSUE TITLE
Issues with other plugins

### ISSUE THREAD

**Issue by miqmago** [roberthovhannisyan/cordova-plugin-google-play-services#1]
Hi Robert,

I've seen you are using id="com.google.play.services" which is causing issues with other plugins: http://stackoverflow.com/questions/33725230/phonegapbuild-google-admob-and-googlemaps-plugins-conflict

Could you please change the id of the plugin in order to avoid conflicts? (com.google.play.services is already taken by https://github.com/appfeel/google-play-services) Thanks!!

**Comment by roberthovhannisyan** [comment]
Hi @miqmago,
I have double checked the issue and it apperas that the problem is NOT in the name of the plugin, but rather in the file 'version.xml', which both plugins are trying to copy to 'res/values' folder.
This means that the problem is not specifically in this plugin ...
One solution could be to use frameworks which are already supported in pbg however I have no ready solution yet ..

**Comment by miqmago** [comment]
Well, I think if you change the name of the plugin, then the files would be copied in different folder and there would be no issue...

**Comment by miqmago** [comment]
(Take in mind that cordova copies all files under a folder named by the id of the plugin :)

**Comment by miqmago** [comment]
Right now the depencencies of https://github.com/appfeel/admob-google-cordova has been updated and they use gradle. There should be no conflict at all right now.

**Comment by wasa4587** [comment]
I can give some details about it, i've been testing for some time. 
if the the maps loads first than admobs, the map disappear.
if admobs loads first than maps, the map is loaded on down,  admobs on top, even if the bannerAtTop is false.
if the maps leads first than admobs and overlap is true, it works only the first time.
i didn't see any style/css changes, nor errors on adb
